# Generated by Django 5.1.5 on 2025-04-09 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('meta_cmv', models.FloatField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mob_no', models.CharField(blank=True, max_length=15, null=True)),
                ('identidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('mrx_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.freelance')),
            ],
        ),
    ]
