# Generated by Django 5.1.5 on 2025-04-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreelanceEvento',
            new_name='Freelance_Evento',
        ),
    ]
