# Generated by Django 5.1.5 on 2025-08-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('eventix', 'Eventix'), ('empresa', 'Empresa')], default='freelancer', max_length=20),
        ),
    ]
