# Generated by Django 5.1.5 on 2025-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EVENTIX', 'Eventix'), ('EMPREGADOR', 'Empregador'), ('FREELANCER', 'Freelancer')], max_length=20),
        ),
    ]
