# Generated by Django 5.1.5 on 2025-08-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Função',
                'verbose_name_plural': 'Categorias de Função',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'ordering': ['nome'], 'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EVENTIX', 'Eventix'), ('CONTRATANTE', 'Contratante'), ('FREELANCER', 'Freelancer')], max_length=20),
        ),
        migrations.AddField(
            model_name='funcao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes', to='app_eventos.categoriafuncao'),
        ),
        migrations.AlterUniqueTogether(
            name='funcao',
            unique_together={('categoria', 'nome')},
        ),
    ]
