# Generated by Django 5.1.5 on 2025-08-19 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_versaosistema_aluguelequipamento_backupsistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Tipo')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato hexadecimal (#RRGGBB)', max_length=7)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa_contratante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financeiras', to='app_eventos.empresacontratante', verbose_name='Empresa Contratante')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'unique_together': {('empresa_contratante', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='DespesaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='app_eventos.categoriafinanceira', verbose_name='Categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='app_eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Despesa do Evento',
                'verbose_name_plural': 'Despesas do Evento',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='EventoFreelancerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(help_text='Horário de chegada')),
                ('horario_fim', models.TimeField(help_text='Horário de saída')),
                ('cache', models.DecimalField(decimal_places=2, help_text='Valor do cachê', max_digits=8)),
                ('prazo_pagamento', models.CharField(default='até 7 dias após o evento', help_text='Prazo de pagamento', max_length=100)),
                ('beneficios', models.CharField(blank=True, help_text='Ex.: Lanche incluso, transporte', max_length=200, null=True)),
                ('funcao', models.CharField(help_text='Função do freelancer, ex.: Garçom, Bar, Caixa', max_length=100)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_info', to='app_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='app_eventos.categoriafinanceira', verbose_name='Categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='app_eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Receita do Evento',
                'verbose_name_plural': 'Receitas do Evento',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
