# Generated by Django 5.1.5 on 2025-08-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0003_categoriafuncao_alter_funcao_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ARENA', 'Arena / Ginásio'), ('PARQUE', 'Parque / Área Aberta'), ('CASA_SHOW', 'Casa de Show'), ('SALAO', 'Salão / Centro de Eventos'), ('ESTABELECIMENTO', 'Estabelecimento Comercial'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em manutenção')], default='ATIVO', max_length=20)),
                ('logradouro', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=12, null=True)),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=60, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidade_pessoas', models.PositiveIntegerField(blank=True, null=True)),
                ('possui_estacionamento', models.BooleanField(default=False)),
                ('possui_acessibilidade', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('contato_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('contato_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('contato_telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa responsável/locatária do local (opcional).', on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='app_eventos.empresa')),
            ],
            options={
                'verbose_name': 'Local de Evento',
                'verbose_name_plural': 'Locais de Evento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='app_eventos.localevento'),
        ),
        migrations.AddIndex(
            model_name='localevento',
            index=models.Index(fields=['cidade', 'estado'], name='app_eventos_cidade_17c9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='localevento',
            index=models.Index(fields=['status'], name='app_eventos_status_a023c7_idx'),
        ),
    ]
