# Generated by Django 5.1.5 on 2025-08-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_tipoempresa_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.vaga'),
        ),
        migrations.CreateModel(
            name='CandidaturaFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_freelance', to='app_eventos.freelance')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.vaga')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='observacoes',
        ),
        migrations.CreateModel(
            name='AlocacaoFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alocacao', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='app_eventos.freelance')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='app_eventos.vaga')),
            ],
            options={
                'verbose_name': 'Alocação de Freelance',
                'verbose_name_plural': 'Alocações de Freelance',
                'unique_together': {('vaga', 'freelance')},
            },
        ),
    ]
