# Generated by Django 5.1.5 on 2025-08-15 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_alter_candidatura_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaturafreelance',
            name='freelance',
        ),
        migrations.RemoveField(
            model_name='candidaturafreelance',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='freelance',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='freelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_pendentes', to='app_eventos.freelance'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='app_eventos.vaga'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContratacaoFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='app_eventos.freelance')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelances_contratados', to='app_eventos.vaga')),
            ],
        ),
        migrations.DeleteModel(
            name='AlocacaoFreelance',
        ),
        migrations.DeleteModel(
            name='CandidaturaFreelance',
        ),
    ]
