# Generated by Django 5.1.5 on 2025-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_migrate_fornecedor_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofuncao',
            options={'verbose_name': 'Tipo de Função', 'verbose_name_plural': 'Tipos de Função'},
        ),
        migrations.AlterUniqueTogether(
            name='tipofuncao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tipofuncao',
            name='nome',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.RemoveField(
            model_name='tipofuncao',
            name='empresa_contratante',
        ),
    ]
