# Generated by Django 5.1.5 on 2025-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_remove_candidaturafreelance_freelance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='arquivo_exame',
            field=models.FileField(blank=True, null=True, upload_to='freelancers/exames/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='carga_horaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='carteira_trabalho_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='carteira_trabalho_serie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='certificado_reservista',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cnh_categoria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cnh_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='data_exame_admissional',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='data_rescisao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='escala_trabalho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/fotos/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='medico_examinador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='observacoes_medicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='resultado_exame',
            field=models.CharField(blank=True, choices=[('apto', 'Apto'), ('inapto', 'Inapto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('pix', 'PIX')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('intermitente', 'Intermitente'), ('freelancer', 'Freelancer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='uf_rg',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='validade_aso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelance',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
