# Generated by Django 5.1.5 on 2025-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_remove_empresa_from_tipofuncao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacontratante',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'cnpj'), name='uniq_fornecedor_por_tenant'),
        ),
    ]
