# Generated by Django 5.1.5 on 2025-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0007_alter_empresacontratante_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterUniqueTogether(
            name='canalcomunicacao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaequipamento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoriafinanceira',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoriainsumo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='controleequipamento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='equipamentosetor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='insumoevento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='insumosetor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='integracaoapi',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='statusequipamento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='templatedocumento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipoveiculo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='despesaevento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='data_vencimento',
            field=models.DateField(db_index=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='codigo_patrimonial',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Código Patrimonial'),
        ),
        migrations.AlterField(
            model_name='equipamentosetor',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('indisponivel', 'Indisponível')], db_index=True, default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código do Insumo'),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='canalcomunicacao',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_canal_comunicacao_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriaequipamento',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_categoria_equipamento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_categoria_financeira_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriainsumo',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_categoria_insumo_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='controleequipamento',
            constraint=models.UniqueConstraint(fields=('equipamento', 'tipo_controle'), name='uniq_controle_por_equipamento'),
        ),
        migrations.AddConstraint(
            model_name='despesaevento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_pagamento__isnull', False), ('status', 'pago')), models.Q(('status', 'pago'), _negated=True), _connector='OR'), name='despesa_pago_tem_data'),
        ),
        migrations.AddConstraint(
            model_name='despesaevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='despesa_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'cnpj'), name='uniq_empresa_cnpj_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='equipamentosetor',
            constraint=models.UniqueConstraint(fields=('setor', 'equipamento'), name='uniq_equipamento_por_setor'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='evento_fim_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='insumoevento',
            constraint=models.UniqueConstraint(fields=('evento', 'insumo'), name='uniq_insumo_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='insumosetor',
            constraint=models.UniqueConstraint(fields=('setor', 'insumo_evento'), name='uniq_insumo_evento_por_setor'),
        ),
        migrations.AddConstraint(
            model_name='integracaoapi',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_integracao_api_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='receitaevento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_recebimento__isnull', False), ('status', 'recebido')), models.Q(('status', 'recebido'), _negated=True), _connector='OR'), name='receita_recebido_tem_data'),
        ),
        migrations.AddConstraint(
            model_name='receitaevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='receita_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='statusequipamento',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_status_equipamento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='templatedocumento',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_template_documento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tipoveiculo',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'nome'), name='uniq_tipo_veiculo_por_tenant'),
        ),
    ]
