# Generated by Django 5.1.5 on 2025-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0007_freelance_agencia_freelance_arquivo_exame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='arquivo_exame',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='crm_medico',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='data_exame_admissional',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='medico_examinador',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='resultado_exame',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='validade_aso',
        ),
        migrations.AddField(
            model_name='freelance',
            name='arquivo_comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='freelancers/documentos/comprovante_residencia/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='arquivo_exame_medico',
            field=models.FileField(blank=True, null=True, upload_to='freelancers/documentos/exame_medico/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='arquivo_identidade_frente',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/documentos/identidade/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='arquivo_identidade_verso',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/documentos/identidade/'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='cadastro_completo',
            field=models.BooleanField(default=False),
        ),
    ]
