# Generated by Django 5.1.5 on 2025-08-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0008_remove_freelance_arquivo_exame_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratacaoFreelance',
            new_name='ContratoFreelance',
        ),
    ]
