# Generated by Django 5.1.5 on 2025-09-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0008_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(default='Equipamento', max_length=200, verbose_name='Nome do Equipamento'),
        ),
        migrations.AddField(
            model_name='localevento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='setorevento',
            name='capacidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade de Pessoas'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_eventos.funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='despesaevento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
