# Generated by Django 5.1.5 on 2025-08-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0009_rename_contratacaofreelance_contratofreelance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='data_rescisao',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='escala_trabalho',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='tipo_vinculo',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='valor_hora',
        ),
    ]
