# Generated by Django 5.2.5 on 2025-09-07 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0010_appfieldworker_avaliacaoevento_avaliacaofornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código da Permissão')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Permissão')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Permissão do Sistema',
                'verbose_name_plural': 'Permissões do Sistema',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo_grupo', models.CharField(choices=[('sistema', 'Grupo do Sistema'), ('empresa', 'Grupo da Empresa'), ('evento', 'Grupo de Evento')], default='empresa', max_length=20)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa_contratante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_usuarios', to='app_eventos.empresacontratante', verbose_name='Empresa Contratante')),
                ('permissoes', models.ManyToManyField(blank=True, related_name='grupos', to='app_eventos.permissaosistema', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Grupo de Usuário',
                'verbose_name_plural': 'Grupos de Usuários',
                'ordering': ['tipo_grupo', 'nome'],
                'unique_together': {('nome', 'empresa_contratante')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_grupo', to='app_eventos.grupousuario', verbose_name='Grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário no Grupo',
                'verbose_name_plural': 'Usuários nos Grupos',
                'ordering': ['-data_entrada'],
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
