# Generated by Django 5.2.5 on 2025-09-09 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0012_configuracaonotificacao_notificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('expert', 'Expert')], default='iniciante', max_length=20, verbose_name='Nível de Proficiência')),
                ('data_adicionada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='app_eventos.freelance', verbose_name='Freelancer')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='app_eventos.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função do Freelancer',
                'verbose_name_plural': 'Funções dos Freelancers',
                'ordering': ['-data_adicionada'],
                'unique_together': {('freelancer', 'funcao')},
            },
        ),
    ]
