# Generated by Django 5.1.5 on 2025-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0013_freelancerfuncao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='empresa',
            name='uniq_empresa_cnpj_por_tenant',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresa_contratante',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
