# Generated by Django 5.1.5 on 2025-09-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0015_planocontratacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localevento',
            name='empresa_contratante',
        ),
    ]
