# Generated by Django 5.1.5 on 2025-09-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0016_remove_localevento_empresa_contratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontratante',
            name='plano_contratado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_contratantes', to='app_eventos.planocontratacao', verbose_name='Plano Contratado (FK)'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='empresa_contratante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_eventos.empresacontratante', verbose_name='Empresa Contratante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='plano_contratado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plano Contratado'),
        ),
    ]
