# Generated by Django 5.1.5 on 2025-09-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0017_empresacontratante_plano_contratado_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='empresa_contratante_recursos',
        ),
        migrations.AlterField(
            model_name='evento',
            name='empresa_contratante',
            field=models.ForeignKey(default=1, help_text='Empresa que cria e gerencia o evento no Eventix, contrata mão de obra e faz toda logística', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_eventos.empresacontratante', verbose_name='Empresa Contratante (Operadora)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='empresa_produtora',
            field=models.ForeignKey(blank=True, help_text='Empresa que concede/fornece a oportunidade do evento (apenas referência, não opera no sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_produzidos', to='app_eventos.empresa', verbose_name='Empresa Produtora (Concedente)'),
        ),
    ]
