# Generated by Django 5.1.5 on 2025-09-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0018_remove_evento_empresa_contratante_recursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresacontratante',
            name='plano_contratado_fk',
        ),
        migrations.AlterField(
            model_name='empresacontratante',
            name='plano_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_contratantes', to='app_eventos.planocontratacao', verbose_name='Plano Contratado'),
        ),
    ]
