# Generated by Django 5.1.5 on 2025-09-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0019_remove_plano_contratado_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontratacao',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Percentual que o Eventix cobra da empresa contratante sobre o valor das vagas (ex: 6% sobre R$ 100 = R$ 6 de comissão + R$ 100 para o freelancer = R$ 106 total)', max_digits=5, verbose_name='Percentual de Comissão (%)'),
        ),
        migrations.CreateModel(
            name='ComissaoEventix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_vaga_freelancer', models.DecimalField(decimal_places=2, help_text='Valor que será pago para o freelancer', max_digits=10, verbose_name='Valor da Vaga (Freelancer)')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Comissão (%)')),
                ('valor_comissao_eventix', models.DecimalField(decimal_places=2, help_text='Valor da comissão que a empresa paga para o Eventix', max_digits=10, verbose_name='Valor da Comissão (Eventix)')),
                ('valor_total_empresa', models.DecimalField(decimal_places=2, help_text='Valor total que a empresa paga (vaga + comissão)', max_digits=10, verbose_name='Valor Total (Empresa)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('calculada', 'Calculada'), ('cobrada', 'Cobrada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('data_cobranca', models.DateTimeField(blank=True, null=True, verbose_name='Data da Cobrança')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contrato_freelance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissao_eventix', to='app_eventos.contratofreelance', verbose_name='Contrato do Freelancer')),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_eventix', to='app_eventos.empresacontratante', verbose_name='Empresa Contratante')),
            ],
            options={
                'verbose_name': 'Comissão do Eventix',
                'verbose_name_plural': 'Comissões do Eventix',
                'ordering': ['-data_calculo'],
            },
        ),
    ]
