# Generated by Django 5.1.5 on 2025-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0022_candidaturaempresa_configuracaodocumentosempresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipofuncao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tipofuncao',
            name='nome',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.RemoveField(
            model_name='tipofuncao',
            name='empresa_contratante',
        ),
    ]
