# Generated by Django 5.1.5 on 2025-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0023_alter_tipofuncao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='device_token',
            field=models.CharField(blank=True, help_text='Token FCM para notificações push', max_length=255, null=True, verbose_name='Token do Dispositivo'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='notificacoes_ativas',
            field=models.BooleanField(default=True, help_text='Se o freelancer deseja receber notificações push', verbose_name='Notificações Ativas'),
        ),
    ]
