# Generated by Django 5.2.2 on 2025-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0025_adiciona_evento_vaga_setor_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='codigo_telefonico_pais',
            field=models.CharField(default='55', help_text='Código do país para formatação internacional (ex: 55 para Brasil)', max_length=5, verbose_name='Código Telefônico do País'),
        ),
    ]
