# Generated by Django 5.1.5 on 2025-11-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0026_freelance_codigo_telefonico_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código único do módulo (ex: 'catering', 'basico')", max_length=50, unique=True, verbose_name='Código do Módulo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo')),
                ('descricao', models.TextField(verbose_name='Descrição do Módulo')),
                ('modulo_basico', models.BooleanField(default=False, help_text='Se True, este módulo está incluído em todos os contratos (mínimo operável)', verbose_name='Módulo Básico')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mensal do módulo (0 para módulos básicos)', max_digits=10, verbose_name='Valor Mensal')),
                ('valor_anual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual do módulo (opcional)', max_digits=10, null=True, verbose_name='Valor Anual')),
                ('funcionalidades', models.JSONField(default=list, help_text='Lista de funcionalidades inclusas no módulo', verbose_name='Funcionalidades')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo do Sistema',
                'verbose_name_plural': 'Módulos do Sistema',
                'ordering': ['modulo_basico', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='modulos_contratados',
            field=models.ManyToManyField(blank=True, help_text='Módulos adicionais contratados pela empresa', related_name='empresas_contratantes', to='app_eventos.modulosistema', verbose_name='Módulos Contratados'),
        ),
    ]
