# Generated by Django 5.2.8 on 2026-04-01 04:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0028_add_ponto_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento ao qual a vaga pertence (deixe vazio se for vaga de Ponto de Operação)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_diretas', to='app_eventos.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='setor',
            field=models.ForeignKey(blank=True, help_text='Setor específico do evento (deixe vazio para vaga genérica ou Ponto de Operação)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_eventos.setorevento', verbose_name='Setor (Opcional)'),
        ),
        migrations.CreateModel(
            name='FichamentoSemanaFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_quarta_inicio', models.DateField(help_text='Deve ser uma quarta-feira; a semana vai até a terça seguinte.', verbose_name='Quarta-feira de abertura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichamentos_pagamento_freelancer', to='app_eventos.empresacontratante', verbose_name='Empresa (tenant)')),
                ('ponto_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichamentos_pagamento_freelancer', to='app_eventos.pontooperacao', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Fichamento semanal (pagamento freelancer)',
                'verbose_name_plural': 'Fichamentos semanais (pagamento freelancer)',
                'ordering': ['-data_quarta_inicio', 'ponto_operacao_id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoDescontoFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vale', 'Vale'), ('consumo', 'Consumo'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor positivo a abater do bruto.', max_digits=12, verbose_name='Valor do desconto')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('data', models.DateField(blank=True, help_text='Opcional; use para alinhar ao dia do vale/consumo.', null=True, verbose_name='Data de referência')),
                ('fichamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_desconto', to='app_eventos.fichamentosemanafreelancer', verbose_name='Fichamento')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_desconto_fichamento', to='app_eventos.freelance', verbose_name='Freelancer')),
            ],
            options={
                'verbose_name': 'Lançamento de desconto (vale/consumo)',
                'verbose_name_plural': 'Lançamentos de desconto (vales/consumos)',
                'ordering': ['fichamento_id', 'freelance_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoPagoDiarioFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor bruto (pago)')),
                ('eh_folga', models.BooleanField(default=False, verbose_name='Folga')),
                ('fichamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_pago', to='app_eventos.fichamentosemanafreelancer', verbose_name='Fichamento')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_pago_fichamento', to='app_eventos.freelance', verbose_name='Freelancer')),
            ],
            options={
                'verbose_name': 'Lançamento pago (diário)',
                'verbose_name_plural': 'Lançamentos pagos (diários)',
                'ordering': ['data', 'freelance_id'],
            },
        ),
        migrations.AddIndex(
            model_name='fichamentosemanafreelancer',
            index=models.Index(fields=['empresa_contratante', 'ponto_operacao', 'data_quarta_inicio'], name='app_eventos_empresa_8d2891_idx'),
        ),
        migrations.AddConstraint(
            model_name='fichamentosemanafreelancer',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'ponto_operacao', 'data_quarta_inicio'), name='uniq_fichamento_semana_por_estabelecimento'),
        ),
        migrations.AddConstraint(
            model_name='lancamentopagodiariofreelancer',
            constraint=models.UniqueConstraint(fields=('fichamento', 'freelance', 'data'), name='uniq_pago_diario_por_freelance_data'),
        ),
    ]
