# Generated by Django 5.2.8 on 2026-04-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0031_lancamento_contrato_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerPrestacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo na lista')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Freelancer com histórico na empresa',
                'verbose_name_plural': 'Freelancers com histórico na empresa',
                'ordering': ['empresa_contratante_id', 'freelance__nome_completo'],
            },
        ),
        migrations.AlterModelOptions(
            name='fichamentosemanafreelancer',
            options={'ordering': ['-data_fechamento', 'ponto_operacao_id'], 'verbose_name': 'Fichamento semanal (pagamento freelancer)', 'verbose_name_plural': 'Fichamentos semanais (pagamento freelancer)'},
        ),
        migrations.RenameIndex(
            model_name='fichamentosemanafreelancer',
            new_name='app_eventos_empresa_43fe21_idx',
            old_name='app_eventos_empresa_fe_idx',
        ),
        migrations.AddField(
            model_name='freelancerprestacaoservico',
            name='empresa_contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers_prestacao_servico', to='app_eventos.empresacontratante', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='freelancerprestacaoservico',
            name='freelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacao_servico_empresas', to='app_eventos.freelance', verbose_name='Freelancer'),
        ),
        migrations.AddIndex(
            model_name='freelancerprestacaoservico',
            index=models.Index(fields=['empresa_contratante', 'ativo'], name='app_eventos_empresa_de81c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='freelancerprestacaoservico',
            constraint=models.UniqueConstraint(fields=('empresa_contratante', 'freelance'), name='uniq_freelancer_prestacao_por_empresa'),
        ),
    ]
