# Generated by Django 5.2.8 on 2026-04-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0032_freelancer_prestacao_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRecorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='Nome da regra')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias 0–6 (segunda=0 … domingo=6, como date.weekday()).')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_fim', models.TimeField(verbose_name='Hora fim')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de recorrência',
                'verbose_name_plural': 'Regras de recorrência',
                'ordering': ['unidade_id', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('evento', 'Evento (pontual)'), ('operacao', 'Operação contínua')], max_length=20, verbose_name='Modo de operação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Início (opcional)')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim (opcional)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_operacionais', to='app_eventos.empresacontratante', verbose_name='Empresa (tenant)')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_operacionais', to='app_eventos.evento', verbose_name='Evento')),
                ('ponto_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_operacionais', to='app_eventos.pontooperacao', verbose_name='Estabelecimento / ponto de operação')),
            ],
            options={
                'verbose_name': 'Unidade operacional',
                'verbose_name_plural': 'Unidades operacionais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TurnoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_fim', models.TimeField(verbose_name='Hora fim')),
                ('origem', models.CharField(choices=[('recorrencia', 'Recorrência'), ('manual', 'Manual')], default='recorrencia', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('regra_recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_gerados', to='app_eventos.regrarecorrencia', verbose_name='Regra que gerou o turno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='app_eventos.unidadeoperacional', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Turno operacional',
                'verbose_name_plural': 'Turnos operacionais',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='regrarecorrencia',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_recorrencia', to='app_eventos.unidadeoperacional', verbose_name='Unidade operacional'),
        ),
        migrations.CreateModel(
            name='VagaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total', models.PositiveIntegerField(verbose_name='Vagas totais')),
                ('quantidade_preenchida', models.PositiveIntegerField(default=0, verbose_name='Preenchidas')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_turno', to='app_eventos.funcao', verbose_name='Função')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_turno', to='app_eventos.turnooperacional', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Vaga do turno',
                'verbose_name_plural': 'Vagas dos turnos',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_turno', to='app_eventos.freelance', verbose_name='Freelancer')),
                ('vaga_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='app_eventos.vagaturno', verbose_name='Vaga do turno')),
            ],
            options={
                'verbose_name': 'Alocação (turno)',
                'verbose_name_plural': 'Alocações (turnos)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraRecorrenciaFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade por turno')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_recorrencia_demanda', to='app_eventos.funcao', verbose_name='Função')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_por_funcao', to='app_eventos.regrarecorrencia', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Demanda por função (regra)',
                'verbose_name_plural': 'Demandas por função (regras)',
                'constraints': [models.UniqueConstraint(fields=('regra', 'funcao'), name='uniq_regra_funcao_demanda')],
            },
        ),
        migrations.AddConstraint(
            model_name='unidadeoperacional',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evento__isnull', False), ('ponto_operacao__isnull', True), ('tipo', 'evento')), models.Q(('evento__isnull', True), ('ponto_operacao__isnull', False), ('tipo', 'operacao')), _connector='OR'), name='unidade_operacional_evento_ou_ponto'),
        ),
        migrations.AddIndex(
            model_name='turnooperacional',
            index=models.Index(fields=['unidade', 'data', 'status'], name='app_eventos_unidade_03168b_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnooperacional',
            constraint=models.UniqueConstraint(fields=('unidade', 'data', 'hora_inicio', 'hora_fim'), name='uniq_turno_unidade_data_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='vagaturno',
            constraint=models.UniqueConstraint(fields=('turno', 'funcao'), name='uniq_vaga_turno_funcao'),
        ),
        migrations.AddConstraint(
            model_name='vagaturno',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_preenchida__lte', models.F('quantidade_total'))), name='vaga_turno_preenchida_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoturno',
            constraint=models.UniqueConstraint(fields=('vaga_turno', 'freelance'), name='uniq_alocacao_vaga_turno_freelance'),
        ),
    ]
