# Generated by Django 5.2.8 on 2026-04-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0033_unidade_operacional_recorrencia_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCalendarioTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: Véspera de Natal', max_length=200, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_calendario_tarifa', to='app_eventos.empresacontratante', verbose_name='Empresa')),
                ('ponto_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_calendario_tarifa', to='app_eventos.pontooperacao', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Data especial (tarifa)',
                'verbose_name_plural': 'Datas especiais (tarifas)',
                'ordering': ['data'],
                'constraints': [models.UniqueConstraint(fields=('ponto_operacao', 'data'), name='uniq_data_tarifa_ponto_data')],
            },
        ),
        migrations.CreateModel(
            name='TarifaDiariaPorFuncaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_turno_dia', models.DecimalField(decimal_places=2, help_text='Ex.: turno comercial / manhã-tarde conforme corte horário.', max_digits=10, verbose_name='Diária turno dia')),
                ('valor_turno_noite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária turno noite')),
                ('valor_noite_especial', models.DecimalField(decimal_places=2, help_text='Sexta e sábado à noite, e noites em datas de véspera cadastradas.', max_digits=10, verbose_name='Noite especial')),
                ('hora_corte_dia_noite', models.TimeField(default='18:00', verbose_name='A partir desta hora = noite (mesmo dia)')),
                ('hora_fim_madrugada_noite', models.TimeField(default='06:00', verbose_name='Antes desta hora = ainda noite (madrugada)')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_diaria_turno', to='app_eventos.empresacontratante', verbose_name='Empresa (tenant)')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_diaria_turno', to='app_eventos.funcao', verbose_name='Função / especialidade')),
                ('ponto_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_diaria_turno', to='app_eventos.pontooperacao', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Tarifa diária por função (estabelecimento)',
                'verbose_name_plural': 'Tarifas diárias por função (estabelecimento)',
                'constraints': [models.UniqueConstraint(fields=('empresa_contratante', 'ponto_operacao', 'funcao'), name='uniq_tarifa_ponto_funcao')],
            },
        ),
    ]
