# Generated by Django 5.2.8 on 2026-04-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0034_tarifa_diaria_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontratante',
            name='modo_dashboard',
            field=models.CharField(choices=[('operacao', 'Só operação e turnos'), ('eventos', 'Só eventos'), ('ambos', 'Operação e eventos')], default='operacao', help_text='Define o foco do menu e da página inicial: operação contínua, eventos ou ambos. Candidaturas e freelancers permanecem disponíveis; financeiro e pagamento a freelancers são opcionais em qualquer modo.', max_length=20, verbose_name='Modo do dashboard'),
        ),
    ]
