# Generated by Django 5.2.8 on 2026-04-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0036_freelance_confiabilidade_presenca'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registropresencafreelancer',
            new_name='app_eventos_freelan_5f208d_idx',
            old_name='app_eventos_freelanc_2b8c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='registropresencafreelancer',
            new_name='app_eventos_empresa_2b57f5_idx',
            old_name='app_eventos_empresa_9f1a2b_idx',
        ),
    ]
